package org.pepsoft.worldpainter.hytale;

import org.junit.Test;
import java.util.List;
import static org.junit.Assert.*;

public class HytaleTerrainPaletteTest {

    @Test
    public void currentPaletteIsAlignedWithLayerIndices() {
        List<String> palette = HytaleTerrain.currentTerrainPaletteBlockIds();
        assertFalse("palette must not be empty", palette.isEmpty());
        // Element (i-1) of the palette must be the block id resolved by layer index i.
        for (int i = 1; i <= palette.size(); i++) {
            HytaleTerrain t = HytaleTerrain.getByLayerIndex(i);
            assertNotNull("no terrain for index " + i, t);
            assertEquals("palette/index mismatch at " + i,
                    (t.getBlock() != null) ? t.getBlock().id : null,
                    palette.get(i - 1));
        }
    }

    @Test
    public void remapByBlockIdHandlesShiftAndRemoval() {
        // Simulated "old" palette: index 1 -> Rock_Stone, index 2 -> Soil_Clay,
        // index 3 -> a block id that no longer exists.
        java.util.Map<Integer, String> oldPalette = new java.util.HashMap<>();
        oldPalette.put(1, "Rock_Stone");
        oldPalette.put(2, "Soil_Clay");
        oldPalette.put(3, "Block_That_Was_Deleted");

        int stoneNow = HytaleTerrain.getByBlockId("Rock_Stone").getLayerIndex();
        int clayNow  = HytaleTerrain.getByBlockId("Soil_Clay").getLayerIndex();

        assertEquals(stoneNow, HytaleTerrainPalette.remapIndex(1, oldPalette));
        assertEquals(clayNow,  HytaleTerrainPalette.remapIndex(2, oldPalette));
        assertEquals("unknown block id clears the pixel",
                0, HytaleTerrainPalette.remapIndex(3, oldPalette));
        assertEquals("index 0 stays 0",
                0, HytaleTerrainPalette.remapIndex(0, oldPalette));
        assertEquals("index absent from palette is left unchanged",
                7, HytaleTerrainPalette.remapIndex(7, oldPalette));
    }

    @Test
    public void remapTilesRewritesStoredClayIndexToCurrentClayIndex() {
        org.pepsoft.worldpainter.Tile tile =
                new org.pepsoft.worldpainter.Tile(0, 0, 0, 320); // x, y, minHeight, maxHeight
        // Pretend this world was saved when "Soil_Clay" lived at stored index 5.
        HytaleTerrainLayer.setTerrainIndex(tile, 10, 10, 5);
        java.util.Map<Integer, String> oldPalette = new java.util.HashMap<>();
        oldPalette.put(5, "Soil_Clay");

        int rewritten = HytaleTerrainPalette.remapTiles(
                java.util.Collections.singletonList(tile), oldPalette);

        assertEquals(1, rewritten);
        int clayNow = HytaleTerrain.getByBlockId("Soil_Clay").getLayerIndex();
        assertEquals(clayNow, HytaleTerrainLayer.getTerrainIndex(tile, 10, 10));
    }

    @Test
    public void preTp57SnapshotReconstructsShiftedClayIndex() {
        java.util.Map<Integer, String> snap = HytaleTerrainV2Snapshot.asPalette();
        assertTrue("snapshot must be populated", snap.size() > 1000);
        assertTrue("snapshot must contain Soil_Clay", snap.containsValue("Soil_Clay"));
        assertTrue("snapshot must contain Rock_Stone", snap.containsValue("Rock_Stone"));

        // The pre-TP-57 index of Soil_Clay must be LOWER than its current index:
        // TP-57 inserted alphabetically-earlier blocks (Metal_*, Plant_*, Rock_*),
        // shifting clay up. This is exactly the regression a pre-TP-57 save hit.
        int preClay = snap.entrySet().stream()
                .filter(e -> "Soil_Clay".equals(e.getValue()))
                .map(java.util.Map.Entry::getKey).findFirst().orElseThrow();
        int currentClay = HytaleTerrain.getByBlockId("Soil_Clay").getLayerIndex();
        assertTrue("pre-TP-57 clay index (" + preClay + ") must be below current ("
                + currentClay + ")", preClay < currentClay);

        // Remapping the OLD clay index through the snapshot yields the CURRENT clay index.
        assertEquals(currentClay, HytaleTerrainPalette.remapIndex(preClay, snap));
    }

    @Test
    public void preTp57SnapshotAccountsForTp65RegistryChange() {
        java.util.Map<Integer, String> snap = HytaleTerrainV2Snapshot.asPalette();

        // The wrong-order Rock_Stone_Mossy_* construction variants existed in the
        // pre-TP-57 registry (generated by addRockVariants("Rock_Stone_Mossy")), so
        // the reconstructed pre-TP-57 palette must still contain them even though
        // TP-65 removed them from the live registry.
        assertTrue("pre-TP-57 snapshot must retain the removed Rock_Stone_Mossy_Cobble",
                snap.containsValue("Rock_Stone_Mossy_Cobble"));
        assertTrue("pre-TP-57 snapshot must retain the removed Rock_Stone_Mossy_Brick",
                snap.containsValue("Rock_Stone_Mossy_Brick"));

        // The two correctly-named blocks TP-65 added did NOT exist pre-TP-57, so they
        // must be excluded from the reconstructed pre-TP-57 ordering (like TP-57 adds).
        assertFalse("pre-TP-57 snapshot must exclude the TP-65-added Rock_Stone_Cobble_Mossy",
                snap.containsValue("Rock_Stone_Cobble_Mossy"));
        assertFalse("pre-TP-57 snapshot must exclude the TP-65-added Rock_Stone_Brick_Mossy",
                snap.containsValue("Rock_Stone_Brick_Mossy"));

        // A pre-TP-57 world that painted the (always-magenta) Rock_Stone_Mossy_Cobble
        // remaps to cleared (block no longer resolves) rather than to a wrong block.
        int preMossyCobble = snap.entrySet().stream()
                .filter(e -> "Rock_Stone_Mossy_Cobble".equals(e.getValue()))
                .map(java.util.Map.Entry::getKey).findFirst().orElseThrow();
        assertEquals("removed block remaps to cleared",
                0, HytaleTerrainPalette.remapIndex(preMossyCobble, snap));

        // A downstream block that existed both eras (Soil_Clay sorts after the mossy
        // region) must still round-trip exactly through the reconstructed palette.
        int preClay = snap.entrySet().stream()
                .filter(e -> "Soil_Clay".equals(e.getValue()))
                .map(java.util.Map.Entry::getKey).findFirst().orElseThrow();
        int currentClay = HytaleTerrain.getByBlockId("Soil_Clay").getLayerIndex();
        assertEquals(currentClay, HytaleTerrainPalette.remapIndex(preClay, snap));

        // The reconstructed auto-generated tail must stay in global String order.
        int curatedCount = HytaleTerrain.getDefaultTerrains().size();
        int max = snap.keySet().stream().max(Integer::compareTo).orElseThrow();
        String prev = null;
        for (int i = curatedCount + 1; i <= max; i++) {
            String id = snap.get(i);
            if (id == null) {
                continue;
            }
            if (prev != null) {
                assertTrue("tail not in String order at index " + i + ": " + prev + " > " + id,
                        prev.compareTo(id) <= 0);
            }
            prev = id;
        }
    }
}
